--- !ditz.rubyforge.org,2008-03-06/project 
name: zeroconf
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: zeroconf
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2012-04-29 13:28:35.007711 Z
    - boisgera <Sebastien.Boisgerault@mines-paristech.fr>
    - created
    - ""
